### ISSUE TITLE
Phase 1 TODO

### ISSUE THREAD

**Issue by tasadurian** [TheTommyTwitch/twitter-project#1]
- [x] Create user profiles
- [x] Fix login button
- [x] Fix Logout button
- [x] Scream button not posting
- [x] Connect profiles to tweets
- [x] Display tweets
- [x] Deploy to app engine
- [x] Display username on tweets
- [ ] Make better modal
- [ ] Make github readme file
- [x] Folowers
- [ ] Add times to tweets
- [x] Add send email on mention
- [ ] Polling
